inicio/urls.py
from django.urls import path
from inicio import views

app_name = 'inicio'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('libros', views.ListaLibro.as_view(), name='lista_libros'),
    path('libro/crear', views.CrearLibro.as_view(), name='crear_libro'),
    path('libro/eliminar/<int:pk>/', views.EliminarLibro.as_view(), name='eliminar_libro'),
    path('libro/modificar/<int:pk>/', views.ModificarLibro.as_view(), name='modificar_libro'),
    path('libro/<int:pk>/', views.MostrarLibro.as_view(), name='mostrar_libro'),
    path('sobre_nosotros/', views.sobre_nosotros, name='sobre_nosotros'),
]

oceano_libros/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('inicio.urls')),
    path('usuario/', include('usuario.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from django.urls import path
from usuario import views
from django.contrib.auth.views import LogoutView

app_name= 'usuario'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', LogoutView.as_view(template_name='usuario/logout.html'), name='logout'),
    path('registro/', views.registrarse, name='registrarse'),
    path('perfil/', views.perfil, name='perfil'),
    path('perfil/editar/', views.editar_perfil, name='editar_perfil'),
    path('perfil/editar/password/', views.ModificarPass.as_view(), name='modificar_pass')
]

inicio/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Libro(models.Model):
    titulo = models.CharField(max_length=50)
    autor = models.CharField(max_length=50)
    editorial = models.CharField(max_length=50)
    precio = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    descripcion = models.TextField(null=True)
    imagen = models.ImageField(upload_to='fotos/', null=True, blank=True)
    propietario = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Libro: {self.titulo} - Autor: {self.autor} - Precio {self.precio} - Editorial: {self.editorial} - Propietario: {self.propietario.username}"
    

usuario/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class InfoExtra(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatares', null=True, blank=True)
    bibliografia = models.TextField(blank=True)

inicio/forms.py
from django import forms
from .models import Libro

class LibroFormularioBase(forms.ModelForm):
    class Meta:
        model = Libro
        fields = ['titulo', 'autor', 'editorial', 'precio', 'descripcion', 'imagen']

class CrearLibroFormulario(LibroFormularioBase):
    ...

class ModificarLibroFormulario(LibroFormularioBase):
    ...

class BusquedaFormulario(forms.Form):
    titulo = forms.CharField(max_length=100, required=False)

inicio/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from inicio.models import Libro
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from inicio.forms import BusquedaFormulario
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from inicio.forms import CrearLibroFormulario, ModificarLibroFormulario
from django.utils import timezone


# Create your views here.

def inicio(request):
    return render(request, 'inicio/inicio.html')

class ListaLibro(ListView):
    model = Libro
    template_name = 'inicio/CBV/lista_libros_CBV.html'
    context_object_name = 'libros'

    def get_queryset(self):
        lista_libros = []
        formulario = BusquedaFormulario(self.request.GET)
        if formulario.is_valid():
            busqueda = formulario.cleaned_data['titulo']
            lista_libros = Libro.objects.filter(titulo__icontains=busqueda)
        return lista_libros

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['formulario'] = BusquedaFormulario()
        return contexto

class CrearLibro(LoginRequiredMixin, CreateView):
    model = Libro
    template_name = 'inicio/CBV/crear_libro_CBV.html'
    form_class = CrearLibroFormulario
    success_url = reverse_lazy('inicio:lista_libros')

    def form_valid(self, form):
        form.instance.propietario = self.request.user
        form.instance.fecha_creacion = timezone.now()
        form.instance.imagen = self.request.FILES.get('imagen')
        return super().form_valid(form)
        
class ModificarLibro(LoginRequiredMixin, UpdateView):
    model = Libro
    template_name = 'inicio/CBV/modificar_libro_CBV.html'
    form_class = ModificarLibroFormulario
    success_url = reverse_lazy('inicio:lista_libros')

    def form_valid(self, form):
        form.instance.imagen = self.request.FILES.get('imagen')
        return super().form_valid(form)

class EliminarLibro(LoginRequiredMixin, DeleteView):
    model = Libro
    template_name ="inicio/CBV/eliminar_libro_CBV.html"
    success_url = reverse_lazy('inicio:lista_libros')

class  MostrarLibro(DetailView):
    model = Libro
    template_name = "inicio/CBV/mostrar_libro_CBV.html"

def sobre_nosotros(request):
    return render(request, 'inicio/sobre_nosotros.html')

usuario/views.py
from django.shortcuts import render, redirect
from usuario.form import FormularioDeCreacionDeUsuarios, FormularioEditarUsuario
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as django_login, authenticate
from usuario.models import InfoExtra
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView

# Create your views here.

def registrarse(request):

    if request.method == 'POST':
        formulario = FormularioDeCreacionDeUsuarios(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect('usuario:login')
        else:
            return render(request, 'usuario/registro.html', {'formulario': formulario})
    formulario = FormularioDeCreacionDeUsuarios()
    return render(request, 'usuario/registro.html', {'formulario': formulario})

def login(request):

    if request.method == 'POST':
        formulario = AuthenticationForm(request, data = request.POST)
        if formulario.is_valid():
            usuario = formulario.cleaned_data['username']
            contraseña = formulario.cleaned_data['password']
            user = authenticate(username=usuario, password=contraseña)
            django_login(request, user)
            InfoExtra.objects.get_or_create(user=user)
            return redirect('inicio:inicio')
        else:
            return render(request, 'usuario/login.html', {'formulario': formulario})
    formulario = AuthenticationForm()
    return render(request, 'usuario/login.html', {'formulario': formulario})

@login_required
def editar_perfil(request):

    info_extra_user = request.user.infoextra
    if request.method == 'POST':
        formulario = FormularioEditarUsuario(request.POST, request.FILES, instance=request.user)
        if formulario.is_valid():
            avatar = formulario.cleaned_data.get('avatar')
            bibliografia = formulario.cleaned_data.get('bibliografia')
            if avatar:
                info_extra_user.avatar = avatar
                info_extra_user.save()
            if bibliografia:
                info_extra_user.bibliografia = bibliografia
                info_extra_user.save()
            formulario.save()
            return redirect('usuario:perfil')
    else:
        formulario = FormularioEditarUsuario(initial={'avatar': info_extra_user.avatar, 'bibliografia': info_extra_user.bibliografia}, instance=request.user)

    return render(request, 'usuario/editar_perfil.html', {'formulario': formulario})

@login_required
def perfil(request):
    usuario = request.user
    info_extra_usuario = InfoExtra.objects.get(user=usuario)

    return render(request, 'usuario/perfil.html', {'usuario': usuario, 'info_extra_usuario': info_extra_usuario})

class ModificarPass(LoginRequiredMixin, PasswordChangeView):
    template_name = 'usuario/modificar_pass.html'
    success_url = reverse_lazy('usuario:perfil')

inicio/templates/inicio/CBV/crear_libro_CBV.html
{% extends 'base.html' %}

{% block title_head %}
<title>Crear Libro</title>
{% endblock title_head %}

{% block h1_header %}
Crear Libro
{% endblock h1_header %}

{% block contenido %}
<form action="{% url 'inicio:crear_libro' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button>Crear</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/CBV/eliminar_libro_CBV.html
{% extends 'base.html' %}

{% block title_head %}
<title>Eliminar Libro</title>
{% endblock title_head %}

{% block h1_header %}
Eliminar Libro
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'inicio:eliminar_libro' libro.id %} method="POST">
    {% csrf_token %}
    <p>Esta seguro de eliminar este libro{{libro}}</p>
    <button>Confirmar</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/CBV/lista_libros_CBV.html
{% extends 'base.html' %}

{% block title_head %}
<title>Libros</title>
{% endblock title_head %}

{% block h1_header %}
Lista de Libros
{% endblock h1_header %}

{% block contenido %}
<button>
    <a class="navbar-brad" href={% url 'inicio:crear_libro' %}>Crear libro</a>
</button>

<form action="" method="get">
    {{ formulario }}
    <button>Buscar</button>
</form>

{% if libros %}
<ul>
    {% for libro in libros %}
    <li>
        Titulo: {{ libro.titulo }} - Autor: {{ libro.autor }} - Precio: ${{ libro.precio }}
        <a href={% url 'inicio:mostrar_libro' libro.id %}>Ver más</a>
        <a href={% url 'inicio:eliminar_libro' libro.id %}>Eliminar</a>
        <a href={% url 'inicio:modificar_libro' libro.id %}>Modificar</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No se encontraron libros con ese nombre, prueba con otro.</p>
{% endif %}
{% endblock contenido %}

inicio/templates/inicio/CBV/modificar_libro_CBV.html
{% extends 'base.html' %}

{% block title_head %}
<title>Modificar Libro</title>
{% endblock title_head %}

{% block h1_header %}
Modificar Libro
{% endblock h1_header %}

{% block contenido %}
<form action="{% url 'inicio:modificar_libro' libro.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button>Modificar</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/CBV/mostrar_libro_CBV.html
{% extends 'base.html' %}

{% block title_head %}
<title>Detealles del Libro</title>
{% endblock title_head %}

{% block h1_header %}
{{libro.titulo}}

{{libro.autor}}
{% endblock h1_header %}

{% block contenido %}
{% if libro.imagen %}
<ul>
    <li>Precio: ${{ libro.precio }}</li>
    <li>Resumen: {{ libro.descripcion }}</li>
    <div class="imagen-libro-container">
        <img src="{{ libro.imagen.url }}" alt="Imagen del libro" class="imagen-libro">
    </div>
    <li>Propietario: {{ libro.propietario.username }}</li>
    <li>Fecha de Creación: {{ libro.fecha_creacion }}</li>
</ul>
{% endif %}
{% endblock contenido %}

inicio/templates/inicio/inicio.html
{% extends 'base.html' %}

{% block title_head %}
<title>Inicio</title>
{% endblock title_head %}

{% block h1_header %}
Bienvenidos al Oceano de Libros
{% endblock h1_header %}

{% block contenido %}

{% endblock contenido %}

inicio/templates/inicio/sobre_nosotros.html
{% extends 'base.html' %}

{% block title_head %}
<title>Nosotros</title>
{% endblock title_head %}

{% block h1_header %}
Sobre Nosotros
{% endblock h1_header %}

{% block contenido %}
<p>
    ¡Bienvenidos a nuestra biblioteca virtual!

    En nuestra biblioteca virtual, nos apasiona fomentar el amor por la lectura y el acceso a la información. Con una
    amplia colección de libros digitales, ofrecemos a nuestros clientes una experiencia única y enriquecedora en el
    mundo de la literatura.

    Nuestro objetivo principal es brindar un espacio inclusivo y accesible para todos los amantes de la lectura. Ya sea
    que estés buscando un clásico atemporal, una novela contemporánea, un libro académico o una emocionante historia de
    ficción, aquí encontrarás una amplia variedad de opciones para satisfacer tus gustos e intereses.

    Nos enorgullece ofrecer una plataforma intuitiva y fácil de usar, que te permitirá navegar por nuestras estanterías
    virtuales y descubrir tesoros literarios sin límites geográficos ni restricciones de horario. Además, nuestra
    biblioteca virtual está disponible en múltiples dispositivos, para que puedas disfrutar de tus libros favoritos en
    cualquier momento y lugar.
</p>
{% endblock contenido %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    {% block title_head %}
    <title>Landing Page - Start Bootstrap Theme</title>
    {% endblock title_head %}
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"
        type="text/css" />
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet"
        type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href={% static "css/styles.css" %} rel="stylesheet" />
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-light bg-light static-top">
        <div class="container">
            <a class="navbar-brand" href={% url 'inicio:inicio' %}>Inicio</a>
            <a class="navbar-brand" href={% url 'inicio:sobre_nosotros' %}>Quiénes Somos</a>
            <a class="navbar-brand" href={% url 'inicio:lista_libros' %}>Lista de Libros</a>
            {% if request.user.is_authenticated %}
            {% if request.user.infoextra.avatar %}
            <img src={{ request.user.infoextra.avatar.url }} alt="" height="40px">
            {% endif %}
            <a class="navbar-brand" href={% url 'usuario:perfil' %}>{{request.user.username}}</a>
            <a class="btn btn-secondary" href={% url 'usuario:logout' %}>Logout</a>
            {% else %}
            <a class="btn btn-primary" href={% url 'usuario:login' %}>Login</a>
            <a class="btn btn-primary" href={% url 'usuario:registrarse' %}>Registrarse</a>
            {% endif %}
        </div>
    </nav>
    <!-- Masthead-->
    <header class="masthead">
        <div class="container position-relative">
            <div class="row justify-content-center">
                <div class="col-xl-6">
                    <div class="text-center text-white">
                        <!-- Page heading-->
                        <h1 class="mb-5">
                            {% block h1_header %}
                            {% endblock h1_header %}
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </header>
    {% block contenido %}
    {% endblock contenido %}
    <!-- Footer-->
    <footer class="footer bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                    <ul class="list-inline mb-2">
                        <li class="list-inline-item"><a href="#!">About</a></li>
                    </ul>
                    <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                </div>
                <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item me-4">
                            <a href="#!"><i class="bi-facebook fs-3"></i></a>
                        </li>
                        <li class="list-inline-item me-4">
                            <a href="#!"><i class="bi-twitter fs-3"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!"><i class="bi-instagram fs-3"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src={% static "js/scripts.js" %}></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>

</html>

usuario/templates/usuario/editar_perfil.html
{% extends 'base.html' %}

{% block title_head %}
<title>Edicion de usuario</title>
{% endblock title_head %}

{% block h1_header %}
Editar perfil
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'usuario:editar_perfil' %} method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <Table>
        {{formulario}}
    </Table>
    <button type="button"> <a class="navbar-brand" href={% url 'usuario:modificar_pass' %}>Cambiar contraseña</a>
    </button>
    <button>Guardar</button>
</form>
{% endblock contenido %}

usuario/templates/usuario/login.html
{% extends 'base.html' %}

{% block title_head %}
<title>Login</title>
{% endblock title_head %}

{% block h1_header %}
Login
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'usuario:login' %} method="POST">
    {% csrf_token %}
    <Table>
        {{formulario}}
    </Table>
    <button>Login</button>
</form>
{% endblock contenido %}

usuario/templates/usuario/logout.html
{% extends 'base.html' %}

{% block title_head %}
<title>Logout</title>
{% endblock title_head %}

{% block h1_header %}
Te deslogeaste con exito!
{% endblock h1_header %}

{% block contenido %}

{% endblock contenido %}

usuario/templates/usuario/modificar_pass.html
{% extends 'base.html' %}

{% block title_head %}
<title>Cambio de contraseña</title>
{% endblock title_head %}

{% block h1_header %}
Editar contraseña
{% endblock h1_header %}

{% block contenido %}
<form action="{% url 'usuario:modificar_pass' %}" method="POST">

    {% csrf_token %}
    <Table>
        {{form}}
    </Table>
    <button>Modificar contraseña</button>
</form>
{% endblock contenido %}

usuario/templates/usuario/perfil.html
{% extends 'base.html' %}

{% block title_head %}
<title>Perfil</title>
{% endblock title_head %}

{% block h1_header %}
{{ usuario.username }}
{% endblock h1_header %}

{% block contenido %}
<li>Email: {{ usuario.email }}</li>
<li>Apellido: {{ usuario.last_name }}</li>
<li>Nombre: {{ usuario.first_name }}</li>
<li>Bibliografia: {{ info_extra_usuario.bibliografia }}</li>
<button><a href={% url 'usuario:editar_perfil' %}>Editar</a></button>
{% endblock contenido %}

usuario/templates/usuario/registro.html
{% extends 'base.html' %}

{% block title_head %}
<title>Registrarse</title>
{% endblock title_head %}

{% block h1_header %}
Registro
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'usuario:registrarse' %} method="POST">
    {% csrf_token %}
    <Table>
        {{formulario}}
    </Table>
    <button>Registrar</button>
</form>
{% endblock contenido %}